name: CI

on:
  push:
    branches:
      - main

env:
  HTTP_PROXY:  http://proxy.corp.example:3128
  HTTPS_PROXY: http://proxy.corp.example:3128
  NO_PROXY:    localhost,127.0.0.1,pixelpoint.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Fetch PixelPoint CSS
        run: curl -I https://pixelpoint.io/
